### ISSUE TITLE
Dark Mode doesn't work with alert

### ISSUE THREAD

**Issue by hendrynm** [mrasyadc/wa-link#4]
Hi, I think the last commit make the problem with alert in the dark mode. The alert not switch into dark mode now.
![image](https://user-images.githubusercontent.com/49647651/91629597-7efca500-e9f4-11ea-8c78-921e6bf61044.png)

The alert should be switch into dark mode like this:
![image](https://user-images.githubusercontent.com/49647651/91629613-af444380-e9f4-11ea-90c4-861e5c7535cb.png)

Can you fix this one? Thank you.

**Comment by mrasyadc** [comment]
i'll try hendry

**Comment by hendrynm** [comment]
Found the problem. So because the Dark Mode button is DOM with a Click sensor, then if after clicking Dark Mode then we just click Create WhatsApp Link, finally Create WA Link by default is in light mode. Actually we can make IF ELSE in each section, so each output must have an output in the form of light mode and dark mode. At least until now, just met like that. Could @mrasyadc have a better solution than this?

**Comment by mrasyadc** [comment]
i have, just see my last commit on dark mode issue @hendrynm

**Comment by hendrynm** [comment]
Wow, great job Rasyad. Thank you 👍
